<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-HOQQ6B4" failures="0" tests="2" name="Surefire test" time="180.994" errors="0" timestamp="2024-06-01T11:00:49 CDT">
  <testcase classname="testcases.BaseClass" name="@BeforeMethod SetUp" time="180.729">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: &amp;apos;DESKTOP-HOQQ6B4&amp;apos;, ip: &amp;apos;192.168.1.133&amp;apos;">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'DESKTOP-HOQQ6B4', ip: '192.168.1.133'
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:537)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:233)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:162)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
at testcases.BaseClass.SetUp(BaseClass.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.18.0', revision: 'b6bf9de7cc*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.19'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:403)
at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:359)
at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:114)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:95)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
... 41 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:386)
... 51 more
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod SetUp -->
  <testcase classname="testcases.BaseClass" name="@AfterMethod QuitBrowser" time="-1.717257649555E9">
    <skipped/>
  </testcase> <!-- @AfterMethod QuitBrowser -->
  <testcase classname="testcases.BaseClass" name="@BeforeMethod SetUp" time="-1.71725764956E9">
    <skipped/>
  </testcase> <!-- @BeforeMethod SetUp -->
  <testcase classname="testcases.BaseClass" name="@AfterMethod QuitBrowser" time="-1.717257649572E9">
    <skipped/>
  </testcase> <!-- @AfterMethod QuitBrowser -->
  <testcase classname="testcases.LoginTest" name="LogiFailureTest" time="0.0">
    <skipped/>
  </testcase> <!-- LogiFailureTest -->
  <testcase classname="testcases.LoginTest" name="LoginSuccessTest" time="0.0">
    <skipped/>
  </testcase> <!-- LoginSuccessTest -->
</testsuite> <!-- Surefire test -->
